services:
  - type: web
    name: hike-ai
    env: docker
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: hike-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RELEASE_VERSION
        value: 1.0.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: CHUTES_API_KEY
        sync: false
      - key: BYTEZ_API_KEY
        sync: false

databases:
  - name: hike-db
    databaseName: hike_ai
    user: hike_user
    plan: free
